### ISSUE TITLE
OSError: esp_eth_driver_install failed

### ISSUE THREAD

**Issue by jingzhaohlj** [emard/esp32lan8720#1]
MicroPython v1.16 on 2021-07-22; ESP32 module with ESP32

Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
OSError: esp_eth_driver_install failed
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
OSError: esp_eth_set_default_handlers failed (invalid parameter)

How to solve this problem?

**Comment by emard** [comment]
HM, it was long time I tried this, it was micropython
1.12 or 1.14 at that time and it was working I have
never seen this error.

currently I have not ready setup connected 
esp32 and lan8270 (but I hope to make it soon)

**Comment by nadolny** [comment]
Test with:

ESP ISO POE - Olimex

Compiling microPython with espressif SDK 4.4 for ESP32

MicroPython v1.19.1-409-g0e8c2204d on 2022-09-19; ESP32 module with ESP32
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
OSError: esp_eth_set_default_handlers failed (invalid parameter)

Same question...

**Comment by nadolny** [comment]
import machine
import network

machine.reset()
lan = network.LAN(Id=0, mdc=machine.Pin(23), mdio=machine.Pin(18), power=None, phy_type=network.PHY_LAN8720, phy_addr=1)
lan.active(1)

The trick was realizing a machine.reset() is needed to change any of the parameters.
ref: https://www.reddit.com/r/esp32/comments/us8w13/ethernet_lan_using_micropython_118_on_the/

Now run Thonny IDE:

MicroPython v1.19.1-409-g0e8c2204d on 2022-09-19; ESP32 module with ESP32
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4344
load:0x40078000,len:13816
load:0x40080400,len:3340
entry 0x40080618
MicroPython v1.19.1-409-g0e8c2204d on 2022-09-19; ESP32 module with ESP32
Type "help()" for more information.

**Comment by dm-vev** [comment]
same issue

```
E (60117) lan8720: lan8720_init(393): wrong chip ID
E (60117) esp_eth: esp_eth_driver_install(199): init phy failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: esp_eth_driver_install failed
```

**Comment by msfmaresca** [comment]
bump. Same issue:  MicroPython v1.27.0 on 2025-12-09; Generic ESP32 module with ESP32
lan = network.LAN(id=0, mdc=machine.Pin(23), mdio=machine.Pin(18), power=None, phy_type=network.PHY_LAN8720, phy_addr=1)
E (14949) esp.emac: emac_esp32_init(548): reset timeout
E (14949) esp_eth: esp_eth_driver_install(250): init mac failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: esp_eth_driver_install failed

Any ideas?
